export var data = [{
    "TreeID" : "TB1S1N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.602)",
    "size" : 30,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
  {
    "TreeID" : "TB1S2N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0408,-75.602)",
    "size" : 30,
    "diameter" : 6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
  {
    "TreeID" : "TB1S3N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.602)",
    "size" : 30,
    "diameter" : 5.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
  {
    "TreeID" : "TB1S4N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0407,-75.602)",
    "size" : 23,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "X",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S5N",
    "Date" : "6/18/2016",
    "Species" : "Princess Cherokee Dogwood",
    "location" : "(40.0409,-75.602)",
    "size" : 17,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark falling off"
  },
{
    "TreeID" : "TB1S6N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0409,-75.602)",
    "size" : 11,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Multi-base"
  },
 {
    "TreeID" : "TB1S7N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0409,-75.602)",
    "size" : 10,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Multi-base"
  },
 {
    "TreeID" : "TB1S8N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0409,-75.602)",
    "size" : 13,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S9N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.602)",
    "size" : 15,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S10N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0408,-75.602)",
    "size" : 19,
    "diameter" : 3.3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S11N",
    "Date" : "6/18/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0411,-75.603)",
    "size" : 25,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S12N",
    "Date" : "6/18/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0410,-75.602)",
    "size" : 30,
    "diameter" : 4.8,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S13N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0411,-75.603)",
    "size" : 25,
    "diameter" : 5.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Canker on the trunk"
  },
 {
    "TreeID" : "TB1S14N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0409,-75.603)",
    "size" : 25,
    "diameter" : 6.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S15N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0411,-75.603)",
    "size" : 25,
    "diameter" : 5.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S16N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0411,-75.603)",
    "size" : 25,
    "diameter" : 5.6,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "",
    "Comments" : "Something stuck in it like a tube"
  },
 {
    "TreeID" : "TB1S17N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.602)",
    "size" : 22,
    "diameter" : 5.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S18N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.602)",
    "size" : 25,
    "diameter" : 5.2,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S19N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0411,-75.602)",
    "size" : 25,
    "diameter" : 4.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S20N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.602)",
    "size" : 25,
    "diameter" : 4.6,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S21N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.602)",
    "size" : 25,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S22N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.602)",
    "size" : 25,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S23N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0411,-75.601)",
    "size" : 35,
    "diameter" : 7.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S24N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0410,-75.601)",
    "size" : 30,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S25N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.601)",
    "size" : 22,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB2S1N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0412,-75.601)",
    "size" : 27,
    "diameter" : 6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB2S2N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0423,-75.600)",
    "size" : 30,
    "diameter" : 8,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S26N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0409,-75.601)",
    "size" : 30,
    "diameter" : 7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S27N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0410,-75.601)",
    "size" : 30,
    "diameter" : 6.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "X",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB2S3N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.601)",
    "size" : 22,
    "diameter" : 5.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S28N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0411,-75.601)",
    "size" : 30,
    "diameter" : 6.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S29N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.601)",
    "size" : 25,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "X",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S30N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.600)",
    "size" : 25,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S31N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0410,-75.600)",
    "size" : 30,
    "diameter" : 5.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Trash"
  },
 {
    "TreeID" : "TB1S32N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0410,-75.600)",
    "size" : 30,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S33N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0410,-75.600)",
    "size" : 30,
    "diameter" : 5.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S34N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.600)",
    "size" : 25,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S35N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.600)",
    "size" : 25,
    "diameter" : 4.3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "At bottom"
  },
 {
    "TreeID" : "TB1S36N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.599)",
    "size" : 20,
    "diameter" : 3.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Branch Decay"
  },
{
    "TreeID" : "TB1S37N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.599)",
    "size" : 15,
    "diameter" : 2.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark peeling Off"
  },
{
    "TreeID" : "TB1S38N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0410,-75.599)",
    "size" : 15,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Bark"
  },
{
    "TreeID" : "TB1S39N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0410,-75.599)",
    "size" : 15,
    "diameter" : 4.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : ""
  },
 {
    "TreeID" : "TB1S40N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0410,-75.599)",
    "size" : 17,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S41N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.599)",
    "size" : 15,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },
  {
    "TreeID" : "TB1S42N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0410,-75.599)",
    "size" : 15,
    "diameter" : 3.4,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },
 {
    "TreeID" : "TB1S43N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.599)",
    "size" : 25,
    "diameter" : 4.3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark at the Bottom"
  },
{
    "TreeID" : "TB1S44N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.598)",
    "size" : 25,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },
{
    "TreeID" : "TB1S45N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.598)",
    "size" : 24,
    "diameter" : 4.7,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },
  {
    "TreeID" : "TB1S46N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0410,-75.598)",
    "size" : 25,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },
 {
    "TreeID" : "TB1S47N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.598)",
    "size" : 25,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S48N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.598)",
    "size" : 25,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB1S49N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0409,-75.598)",
    "size" : 30,
    "diameter" : 5.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB2S4N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0412,-75.601)",
    "size" : 12,
    "diameter" : 2.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB2S5N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0412,-75.600)",
    "size" : 25,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB2S6N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0413,-75.600)",
    "size" : 30,
    "diameter" : 6.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB2S7N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn ",
    "location" : "(40.0414,-75.600)",
    "size" : 15,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB2S8N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0419,-75.599)",
    "size" : 25,
    "diameter" : 4.7,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB2S9N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0420,-75.599)",
    "size" : 40,
    "diameter" : 6.8,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB2S10N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0418,-75.599)",
    "size" : 25,
    "diameter" : 5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB2S11N",
    "Date" : "6/18/2016",
    "Species" : "Red Maple",
    "location" : "(40.0417,-75.600)",
    "size" : 25,
    "diameter" : 4.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB2S12N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0416,-75.600)",
    "size" : 25,
    "diameter" : 4.2,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB2S13N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0414,-75.600)",
    "size" : 30,
    "diameter" : 5.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB2S14N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0423,-75.600)",
    "size" : 35,
    "diameter" : 8,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB1S50N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0408,-75.601)",
    "size" : 15,
    "diameter" : 2.4,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB1S51N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.601)",
    "size" : 18,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark (at bottom)"
  },{
    "TreeID" : "TB1S52N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.601)",
    "size" : 15,
    "diameter" : 3.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Canker at Bottom"
  },{
    "TreeID" : "TB1S53N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.601)",
    "size" : 18,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "At bottom"
  },{
    "TreeID" : "TB1S54N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.601)",
    "size" : 11,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S55N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 11,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S56N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 12,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S57N",
    "Date" : "6/18/2016",
    "Species" : "Princess Cherokee Dogwood",
    "location" : "(40.0408,-75.600)",
    "size" : 12,
    "diameter" : 3.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S58N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 11,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark at bottom"
  },{
    "TreeID" : "TB1S59N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 12,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark at bottom"
  },{
    "TreeID" : "TB1S60N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 14,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S61N",
    "Date" : "6/18/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0408,-75.600)",
    "size" : 15,
    "diameter" : "Multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S62N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.600)",
    "size" : 17,
    "diameter" : 5.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "X",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at bottom"
  },{
    "TreeID" : "TB1S63N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0408,-75.599)",
    "size" : 18,
    "diameter" : 3.9,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S64N",
    "Date" : "6/18/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0407,-75.599)",
    "size" : 18,
    "diameter" : 5.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB1S65N",
    "Date" : "6/18/2016",
    "Species" : "White Oak",
    "location" : "(40.0407,-75.599)",
    "size" : 18,
    "diameter" : 4.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S66N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0406,-75.599)",
    "size" : 30,
    "diameter" : 5.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at Bottom"
  },{
    "TreeID" : "TB1S67N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.600)",
    "size" : 30,
    "diameter" : 4.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at Bottom"
  },{
    "TreeID" : "TB1S68N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.600)",
    "size" : 30,
    "diameter" : 5.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S69N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.600)",
    "size" : 30,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S70N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.600)",
    "size" : 30,
    "diameter" : 5.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at Bottom"
  },{
    "TreeID" : "TB1S71N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0406,-75.600)",
    "size" : 35,
    "diameter" : 6.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Fallen Branch on Top"
  },{
    "TreeID" : "TB1S72N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0406,-75.600)",
    "size" : 30,
    "diameter" : 4.8,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S73N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0406,-75.600)",
    "size" : 35,
    "diameter" : 5.8,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S74N",
    "Date" : "6/18/2016",
    "Species" : "American Elm",
    "location" : "(40.0406,-75.600)",
    "size" : 30,
    "diameter" : 6.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S75N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0407,-75.601)",
    "size" : 28,
    "diameter" : 5.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB1S76N",
    "Date" : "6/18/2016",
    "Species" : "American Sycamore",
    "location" : "",
    "size" : 28,
    "diameter" : 4.4,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S1N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0405,-75.599)",
    "size" : 15,
    "diameter" : 3,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Decay at Bottom, Insects at Top"
  },{
    "TreeID" : "TB3S3N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0403,-75.599)",
    "size" : 22,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at Bottom"
  },{
    "TreeID" : "TB3S5N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0401,-75.599)",
    "size" : 20,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Decay at Bottom"
  },{
    "TreeID" : "TB3S7N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0399,-75.599)",
    "size" : 17,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Canker at Bottom"
  },{
    "TreeID" : "TB3S9N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.396,-75.599)",
    "size" : 21,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Canker at Bottom"
  },{
    "TreeID" : "TB3S11N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0394,-75.599)",
    "size" : 24,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S13N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0391,-75.599)",
    "size" : 23,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S15N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0386,-75.598)",
    "size" : 24,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S17N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0387,-75.598)",
    "size" : 18,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S19N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0385,-75.598)",
    "size" : 25,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S21N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0383,-75.598)",
    "size" : 25,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S23N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0381,-75.598)",
    "size" : 21,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S25N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0383,-75.598)",
    "size" : 19,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Canker at Bottom"
  },{
    "TreeID" : "TB3S27N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0375,-75.598)",
    "size" : 19,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Canker at Bottom"
  },{
    "TreeID" : "TB3S29N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0374,-75.598)",
    "size" : 25,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S1N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0374,-75.598)",
    "size" : 20,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S3N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0371,-75.598)",
    "size" : 12,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Some Canker in Middle"
  },{
    "TreeID" : "TB4S5N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0370,-75.599)",
    "size" : 20,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S7N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0368,-75.599)",
    "size" : 14,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "X",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S9N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0368,-75.599)",
    "size" : 16,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S11N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0367,-75.599)",
    "size" : 20,
    "diameter" : 4,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S13N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0366,-75.600)",
    "size" : 14,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S15N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0365,-75.600)",
    "size" : 21,
    "diameter" : 6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S17N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0364,-75.600)",
    "size" : 18,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "",
    "Comments" : "Tube inside"
  },{
    "TreeID" : "TB4S19N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0363,-75.601)",
    "size" : 18,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "X",
    "insects" : "",
    "Comments" : "Tube inside"
  },{
    "TreeID" : "TB4S21N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0363,-75.601)",
    "size" : 16,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S23N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0363,-75.601)",
    "size" : 21,
    "diameter" : 5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S25N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0365,-75.601)",
    "size" : 14,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S27N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0364,-75.601)",
    "size" : 13,
    "diameter" : 3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S29N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0363,-75.602)",
    "size" : 12,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S31N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0362,-75.602)",
    "size" : 19,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S33N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0361,-75.602)",
    "size" : 22,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB4S35N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0360,-75.603)",
    "size" : 12,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "X",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB4S37N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0360,-75.603)",
    "size" : "",
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB3S2N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0404,-75.599)",
    "size" : 20,
    "diameter" : 14,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "At Bottom"
  }, {
    "TreeID" : "TB3S4N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0402,-75.599)",
    "size" : 18,
    "diameter" : 14.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB3S6N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0400,-75.599)",
    "size" : 18,
    "diameter" : 15,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "3' Up - Bottom"
  },{
    "TreeID" : "TB3S8N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0398,-75.599)",
    "size" : 14,
    "diameter" : 15,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark Damage"
  },{
    "TreeID" : "TB3S10N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0395,-75.599)",
    "size" : 24,
    "diameter" : 16.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB3S12N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0393,-75.599)",
    "size" : 22,
    "diameter" : 15.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "In-grow Band- minor decay"
  },{
    "TreeID" : "TB3S14N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0391,-75.598)",
    "size" : 20,
    "diameter" : 14,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB3S16N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0390,-75.598)",
    "size" : 20,
    "diameter" : 16.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Minor Prune"
  }, {
    "TreeID" : "TB3S18N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0386,-75.598)",
    "size" : 20,
    "diameter" : 17,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB3S20N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0384,-75.598)",
    "size" : 20,
    "diameter" : 15.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Minor Prune"
  }, {
    "TreeID" : "TB3S22N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0382,-75.598)",
    "size" : 20,
    "diameter" : 16,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S24N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0379,-75.598)",
    "size" : 14,
    "diameter" : 12.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB3S26N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0376,-75.598)",
    "size" : 16,
    "diameter" : 14.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Serious Canker"
  }, {
    "TreeID" : "TB3S28N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0375,-75.598)",
    "size" : 16,
    "diameter" : 12.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S2N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0372,-75.598)",
    "size" : 20,
    "diameter" : 15.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S4N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0370,-75.599)",
    "size" : 20,
    "diameter" : 14,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S6N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0370,-75.599)",
    "size" : 20,
    "diameter" : 14.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S8N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0369,-75.599)",
    "size" : 14,
    "diameter" : 13.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Serious at Base"
  },{
    "TreeID" : "TB4S10N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0368,-75.599)",
    "size" : 14,
    "diameter" : 13,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Serious Canker 2' up"
  }, {
    "TreeID" : "TB4S12N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0367,-75.600)",
    "size" : 18,
    "diameter" : 16.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Minor Canker"
  }, {
    "TreeID" : "TB4S14N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0365,-75.600)",
    "size" : 14,
    "diameter" : 13,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bottom"
  },{
    "TreeID" : "TB4S16N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0364,-75.600)",
    "size" : 18,
    "diameter" : 15,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bottom"
  },{
    "TreeID" : "TB4S18N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0364,-75.601)",
    "size" : 16,
    "diameter" : 13,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "In-Grown Band"
  },  {
    "TreeID" : "TB4S20N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0363,-75.601)",
    "size" : 18,
    "diameter" : 15,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S22N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0363,-75.601)",
    "size" : 14,
    "diameter" : 12,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Serious Canker"
  }, {
    "TreeID" : "TB4S24N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0365,-75.601)",
    "size" : 22,
    "diameter" : 16,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S26N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0365,-75.601)",
    "size" : 14,
    "diameter" : 12.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Serious Canker"
  }, {
    "TreeID" : "TB4S28N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0364,-75.602)",
    "size" : 16,
    "diameter" : 11.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S30N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0362,-75.602)",
    "size" : 14,
    "diameter" : 11.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S32N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0361,-75.602)",
    "size" : 16,
    "diameter" : 11.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S34N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0362,-75.602)",
    "size" : 18,
    "diameter" : 11.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S36N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0359,-75.603)",
    "size" : 18,
    "diameter" : 11.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S38N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0359,-75.603)",
    "size" : 14,
    "diameter" : 11,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S39N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0360,-75.603)",
    "size" : 15,
    "diameter" : 3.2,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB4S40N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0360,-75.603)",
    "size" : 17,
    "diameter" : 3.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S41N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0360,-75.603)",
    "size" : 19,
    "diameter" : 3.6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S42N",
    "Date" : "6/19/2016",
    "Species" : "Red MAple",
    "location" : "(40.0361,-75.603)",
    "size" : 16,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S43N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0362,-75.603)",
    "size" : 28,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S44N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0362,-75.603)",
    "size" : 17,
    "diameter" : 3.6,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S45N",
    "Date" : "6/19/2016",
    "Species" : "American Elm",
    "location" : "(40.0364,-75.603)",
    "size" : 35,
    "diameter" : 5.8,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S46N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0367,-75.603)",
    "size" : 16,
    "diameter" : 3.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S47N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0369,-75.602)",
    "size" : 16,
    "diameter" : 3.3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark "
  },{
    "TreeID" : "TB4S48N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0371,-75.602)",
    "size" : 26,
    "diameter" : 4.6,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Weed grass at bottom"
  }, {
    "TreeID" : "TB4S49N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0373,-75.602)",
    "size" : 27,
    "diameter" : 5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Weed grass at bottom"
  },{
    "TreeID" : "TB4S50N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0374,-75.602)",
    "size" : 26,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S51N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0376,-75.602)",
    "size" : 17,
    "diameter" : 4,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB4S52N",
    "Date" : "6/19/2016",
    "Species" : "Red Maple",
    "location" : "(40.0380,-75.602)",
    "size" : 18,
    "diameter" : 4.8,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S53N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0383,-75.602)",
    "size" : 25,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S54N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0380,-75.602)",
    "size" : 25,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S55N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0385,-75.602)",
    "size" : 20.2,
    "diameter" : 3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S56N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0386,-75.602)",
    "size" : 25,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S57N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0387,-75.602)",
    "size" : 18,
    "diameter" : 3.25,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S58N",
    "Date" : "6/19/2016",
    "Species" : "American Elm",
    "location" : "(40,0390,-75.602)",
    "size" : 23,
    "diameter" : 6,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S59N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0390,-75.601)",
    "size" : 25,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB4S60N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0392,-75.601)",
    "size" : 17,
    "diameter" : 3.75,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S61N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0396,-75.602)",
    "size" : 15,
    "diameter" : 5.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S62N",
    "Date" : "6/19/2016",
    "Species" : "American Elm",
    "location" : "(40.0399,-75.601)",
    "size" : 20,
    "diameter" : 4.1,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S63N",
    "Date" : "6/19/2016",
    "Species" : "American Elm",
    "location" : "(40.0401,-75.601)",
    "size" : 23,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB4S64N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0404,-75.601)",
    "size" : 20,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S65N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0403,-75.601)",
    "size" : 18,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S66N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0404,-75.601)",
    "size" : 18,
    "diameter" : 3.7,
    "clean" : "",
    "weed" : "X",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB4S67N",
    "Date" : "6/19/2016",
    "Species" : "American Sycamore",
    "location" : "(40.0405,-75.601)",
    "size" : 17,
    "diameter" : 3.7,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S1N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0395,-75.608)",
    "size" : 17,
    "diameter" : 4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S3N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0395,-75.608)",
    "size" : 19,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S5N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0395,-75.609)",
    "size" : 20,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S7N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0394,-75.609",
    "size" : 20,
    "diameter" : 4.75,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "X",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "X",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S9N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0394,-75.609",
    "size" : 6,
    "diameter" : 2.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "X",
    "Comments" : "***************"
  },{
    "TreeID" : "TB5S11N",
    "Date" : "6/19/2016",
    "Species" : "White Oak",
    "location" : "(40.0394,-75.609",
    "size" : 13,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S13N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0392,-75.609)",
    "size" : 18,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB5S15N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0392,-75.609)",
    "size" : 19,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB5S17N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.0391,-75.609)",
    "size" : 18,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S19N",
    "Date" : "6/19/2016",
    "Species" : "Honey Locust",
    "location" : "(40.391,-75.610)",
    "size" : 19,
    "diameter" : 4.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S2n",
    "Date" : "6/19/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0396,-75.609)",
    "size" : 12,
    "diameter" : "multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB5S4N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0396,-75.609)",
    "size" : 15,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S6N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0396,-75.609)",
    "size" : 15,
    "diameter" : 3.5,
    "clean" : "",
    "weed" : "",
    "prune" : "S",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S8N",
    "Date" : "6/19/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0396,-75.609)",
    "size" : 15,
    "diameter" : "multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S10N",
    "Date" : "6/19/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0396,-75.609)",
    "size" : 15,
    "diameter" : "multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  },{
    "TreeID" : "TB5S12N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0396,-75.609)",
    "size" : 16,
    "diameter" : 3.4,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark little"
  },{
    "TreeID" : "TB5S14N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0396,-75.609)",
    "size" : 15,
    "diameter" : 3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark at bottom"
  }, {
    "TreeID" : "TB5S16N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0396,-75.609)",
    "size" : 13,
    "diameter" : 2.5,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB5S18N",
    "Date" : "6/19/2016",
    "Species" : "Princess Cherokee Dogwood",
    "location" : "(40.0396,-75.609)",
    "size" : 11,
    "diameter" : 3.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  },{
    "TreeID" : "TB5S20N",
    "Date" : "6/19/2016",
    "Species" : "Princess Cherokee Dogwood",
    "location" : "(40.0394,-75.609)",
    "size" : 13,
    "diameter" : 3.2,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB5S22N",
    "Date" : "6/19/2016",
    "Species" : "Winterking Hawthorn",
    "location" : "(40.0394,-75.609)",
    "size" : 17,
    "diameter" : 3.3,
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : "Bark"
  }, {
    "TreeID" : "TB5S24N",
    "Date" : "6/19/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0394,-75.609)",
    "size" : 12,
    "diameter" : "multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
  }, {
    "TreeID" : "TB5S26N",
    "Date" : "6/19/2016",
    "Species" : "Serviceberry",
    "location" : "(40.0393,-75.610)",
    "size" : 12,
    "diameter" : "multi",
    "clean" : "",
    "weed" : "",
    "prune" : "",
    "canker" : "",
    "crack" : "",
    "Cavities" : "",
    "Decay" : "",
    "Gall" : "",
    "insects" : "",
    "Comments" : ""
}]
